### ISSUE TITLE
Manual sort order cannot be remembered by different filter extension

### ISSUE THREAD

**Issue by windslice** [tableau/extension-filter-bookmarks#15]
Background:
I have 2 filters in my worksheet: [step id] & [data id].
For different [step id] filtered, the contents of [data id] is different.

Issue:
The specific values are set for the filters [step id] & [data id] and saved to the extension instances, but when I click the extensions to switch between the [step id], the sort I configured is not saved and restored.
eg:
[step id]: 1,2
[data id] of [step id]/1: a, b, d, g, h, x
[data id] of [step id]/2: a, b, c, d, f, g, h, y, z

Extension 1 to record the filter of [step id]/1, the sort order of [data id] can be manually adjusted to a, d, b, x, g, h
Extension 2 to record the filter of [step id]/2, the sort order of [data id ] is manually adjusted to  a, y, b, c, z, g, h

When I click extension 1, all things working good. but when I click extension 2, the sort is changed(not like what I manually adjusted) to a, b, g, h, c, y, z

Conclusion:
The extension is good, but not support the sort method very well, that makes me upset~

**Comment by KeshiaRose** [comment]
Hi @windslice, manual sorting is not saved per filter in general with Tableau, whether you are using an extension or not. Instead of manually sorting the IDs you should [sort by another field](https://help.tableau.com/current/pro/desktop/en-us/sortgroup_sorting_computed_howto.htm#sort-specific-fields-in-the-viz). If there is no natural field to sort by then you can make a custom calculation like so: 
```
CASE [Step ID]
WHEN 1 THEN 
    CASE [Data ID]
    WHEN "a" THEN 1
    WHEN "d" THEN 2
    WHEN "b" THEN 3
    WHEN "x" THEN 4
    WHEN "g" THEN 5
    WHEN "h" THEN 6
    ELSE 0 END

WHEN 2 THEN
    CASE [Data ID]
    WHEN "a" THEN 1
    WHEN "y" THEN 2
    WHEN "b" THEN 3
    WHEN "c" THEN 4
    WHEN "z" THEN 5
    WHEN "g" THEN 6
    WHEN "h" THEN 7
    ELSE 0 END
ELSE 0 END
```

Then add a sort on your [Data ID] using sort by field, ascending on your custom calculation with minimum aggregation: 
![image](https://user-images.githubusercontent.com/19785852/93798585-c7be0d00-fbf2-11ea-9f96-2eb4f9e7c633.png)

**Comment by windslice** [comment]
Hi Keshia, Thanks a lot for the advice!
