### ISSUE TITLE
Error Code: 4AC8135F on Reverting filters

### ISSUE THREAD

**Issue by litviakk** [tableau/extension-filter-bookmarks#18]
Hello! 
I have a trouble with the extension. When I press a button "Revert Filters" after I saved current filters I see the following error:
Unable to complete action
/Volumes/build/tc/t203/g_pc/modules/platform/tabcore/main/parser/DataValueParser.cpp|ParseInt|486 value - 'NaN-NaN-NaN NaN:NaN:NaN' must have at least one digit
 - Error parsing date '#NaN-NaN-NaN NaN:NaN:NaN#'.
Error Code: 4AC8135F

**Comment by KeshiaRose** [comment]
Hi @litviakk, are you able to replicate this error in a workbook that you could send? It's hard to debug without seeing it myself.

**Comment by litviakk** [comment]
Hi @KeshiaRose, here it is. The extension has already saved state in it, but for some reason the extension is not being shown after I save the workbook
[Vendor Metrics - Anon 2 + ext.twbx.zip](https://github.com/tableau/extension-filter-bookmarks/files/5922112/Vendor.Metrics.-.Anon.2.%2B.ext.twbx.zip)

**Comment by KeshiaRose** [comment]
Thank you, your workbook was invaluable in my investigation. I was able to find the error and have made an update to fix it. Upon reloading the extension you should no longer get the error!

As a side note, I am both impressed and terrified at the number of worksheets in this dashboard! 😆  One thing to note, in the filter bookmarks configuration is that you can select which worksheets you want to apply the filters to. Since you seem to be using a lot of worksheets just to display labels, or as buttons (by the way you can use images for some of these to gain a little performance) you can choose which worksheets to affect instead of affecting all of them. As it looks like you have a lot of data source level filters and filters that update across worksheets you will be able to reduce the number of sheets updated by only selecting a couple of sheets and then letting Tableau update the sheets that are connected.
