### ISSUE TITLE
The name of the build output folder

### ISSUE THREAD

**Issue by iXmerof** [tableau/extension-filter-bookmarks#22]
Hi,
I'd just like to know if that's a convention here or an issue. 
Once I've downloaded the extension and planned to build it locally my steps were:

1. setup recent LTS version of nodejs
2. npm install
3. modification of the 'homepage' entry
3. npm run build

The readme.md mentions that output of this operation should be found in the /build folder, but actually it is a /docs folder.
Same goes for the original folders structure and in package.json the "build" script moves the /build directory to /docs, is this intentional?

Thanks

**Comment by KeshiaRose** [comment]
HI @iXmerof, the output folder is `/docs` as is mentioned in step 5 "Copy the files in docs to your web server at the path you specified in Step 3." The only time it is `/build` is if you followed the note in step 4 "Note, you can update the package.json file to just run react-scripts build, the rest is just to move the folders around. **If you do this**, look for the build folder in the next step." The reason the script moves the files to `/docs` is because that is where GitHub pages is looking for the files to host. Hope this helps!
-Keshia

**Comment by iXmerof** [comment]
Oh, nice one. Thank you
