### ISSUE TITLE
Noticing upwards of 30 second delays

### ISSUE THREAD

**Issue by michaelclarkHDI** [tableau/extension-filter-bookmarks#3]
Not sure if this is a bug , but we are noticing upwards of 30 second delays when using this extension via Tableau Server.  We tried locally and it worked without issue.  Is there perhaps a way to serve this from the Tableau server?

**Comment by KeshiaRose** [comment]
Hi @michaelclarkHDI,

Thank you for your patience in my late response. Have you tried downloading and running the extension on an internal web server? Is your Server hosted in a different region?

Take care,
Keshia

**Comment by kaurtanu93** [comment]
Hi @KeshiaRose,

I am also facing similar issue.
There is around 30 secs of delay in running filter bookmark extension on tableau server.
But works well on Tableau Desktop.
Do we have any solutio nfor this?

Regards,
Taran

**Comment by KeshiaRose** [comment]
Hi @kaurtanu93,

Not sure what would be causing this, there shouldn't be much of a difference. Are the versions of Desktop and Server the same?

Take care,
Keshia

**Comment by KeshiaRose** [comment]
Hi @kaurtanu93,

I'm going to close this as it has been a while, please feel free to re-open if you are still having this issue.

Take care,
Keshia

**Comment by mac471** [comment]
I would like to reopen this issue. I am using Tableau Online 2020.2 and I've noticed that when opening a dashboard page that has this extension, the dashboard displays, waits a second and then proceeds to refresh for another few seconds.  

I am using the new feature where you can specify an image instead of text. I notice that when the dashboard is first displayed, you see the default button text ("Revert Filters") and THEN after the refresh, the image is displayed. (I will file a separate issue for this)

A few seconds isn't a terrible problem but when there are a few extensions on the dashboard (I was also using the exportallextension from theinformationlab.io), the delay becomes noticeable (upwards of 7-10 seconds every time you want to look at the dashboard).

In Tableau Online, I have enabled these extensions with Full Data Access set to Deny and User Prompts set to Hide.  Both checkboxes to "Let users run extensions on this site" and "Let Sandboxed extensions run on this site" are checked.

Shouldn't these extensions be cached after the first load?  We shouldn't be paying this time penalty every time we want to view the dashboard.

Thanks in advance for your help.

**Comment by KeshiaRose** [comment]
Hi @mac471,

For the refresh issue, can you confirm it is the Filter Bookmarks extension that is causing the refresh and not another extension? There isn't anything in initialization that should be affecting the dashboard. 

As for the text button issue, this is happening because when you open a dashboard with an extension first, the extension is loaded, and then it looks at the settings that are saved to the workbook to make any updates. I could also store the settings in browser cache but then the extension would be looking in two places for instructions for what to show. If the dashboard author changes the settings, the extension could potentially show 3 different things: default >> what is in cache >> what is in settings. I think this would be even worse than the current: default >> settings.

One thing I could change would be to show nothing instead of the default button while the settings are being read and then only update with the right image/text settings.

Take care,
Keshia

**Comment by mac471** [comment]
Hi Keshia,

Yes, it is the Filter Bookmarks extension that is causing the refresh delay. I ended up removing the other one because the combined time penalty was too much.  As I said, it's not a huge (e.g. 30 second) delay but it is distracting because you pay the penalty every time you switch to view the dashboard (using tabbed interface). 

And this only happens with Tableau Online - not really noticeable when using Desktop.  I'm thinking that Online isn't caching these extensions for some reason?

**Comment by KeshiaRose** [comment]
Huh, that is really weird, I have no idea why the extension would be causing the dashboard to refresh on initialization. But yes, Tableau Online/Server doesn't keep that iframe loaded so when you switch tabbed views it is reloading the extension again. Unlike in Desktop where the iframe instance remains loaded even when you swap between dashboards.
